### ISSUE TITLE
python unicode failure

### ISSUE THREAD

**Issue by rarkins** [singapore/lint-condo#57]
When running on EC2 Ubuntu 14.04 VM:

```
Summary:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/doit/action.py", line 154, in _print_process_output
    realtime.write(line.encode(encoding))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 5: ordinal not in range(128)
```

From https://github.com/pydoit/doit/issues/125#issuecomment-192625217
> python 2?

> master doesnt even support python2 anymore. If you create a branch from the last release and a pull request with this fix, I can push a new release.

However aren't we using the last release (0.29.0)?

On my mac: Python 2.7.10
On my VM: Python 2.7.6

**Comment by kayoub5** [comment]
@rarkins use python3

**Comment by kayoub5** [comment]
```
apt-get install python3-pip
pip3 install --upgrade doit
doit tabcompletion > /etc/bash_completion.d/doit
```

**Comment by rarkins** [comment]
Colours work but it still errors on the summary at the end:

```
Summary:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/doit/action.py", line 172, in _print_process_output
    realtime.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2714' in position 5: ordinal not in range(128)
```

**Comment by rarkins** [comment]
I think this is related to a unicode locale problem on the VM, so closing.
